from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
import subprocess
import os

app = FastAPI()

# Allow frontend requests
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Ensure the output folder exists
os.makedirs("media", exist_ok=True)

# Serve generated videos at http://your-render-url/media/filename.mp4
app.mount("/media", StaticFiles(directory="media"), name="media")

class MathRequest(BaseModel):
    prompt: str

@app.get("/")
def home():
    return {"status": "Manim Render Service Online"}

@app.post("/api/generate-math-video")
async def generate_math_video(req: MathRequest):
    # 1. Example Manim script (this will later be dynamically generated by an LLM)
    script_content = """
from manim import *

class MathScene(Scene):
    def construct(self):
        title = Text("Solving Math Visually", font_size=36)
        eq = MathTex(r"x^2 - 4x + 3 = 0")
        eq.next_to(title, DOWN)
        self.play(Write(title))
        self.play(Write(eq))
        self.wait(2)
"""
    # 2. Save script to a temporary file
    script_path = "temp_scene.py"
    with open(script_path, "w") as f:
        f.write(script_content)

    # 3. Execute Manim CLI rendering
    # -pql: low quality (renders in ~2-3 seconds for fast API response)
    # --media_dir: sets output location to the mounted 'media' folder
    cmd = ["manim", "-pql", "--media_dir", "media", script_path, "MathScene"]
    subprocess.run(cmd, check=True)

    # 4. Location where Manim places low-quality renders
    # Manim structures default outputs: media/videos/temp_scene/480p15/MathScene.mp4
    rendered_video_path = "media/videos/temp_scene/480p15/MathScene.mp4"
    
    # Move/Copy to a direct static URL route
    public_filename = "math_solution.mp4"
    public_filepath = os.path.join("media", public_filename)
    
    if os.path.exists(rendered_video_path):
        os.replace(rendered_video_path, public_filepath)

    # 5. Return the direct public URL for your video
    render_domain = os.getenv("RENDER_EXTERNAL_URL", "https://manim-backend-regt.onrender.com")
    full_video_url = f"{render_domain}/media/{public_filename}"

    return {
        "status": "success",
        "video_url": full_video_url,
        "latex_steps": [
            r"\text{Identify equation: } x^2 - 4x + 3 = 0",
            r"\text{Factor into: } (x - 1)(x - 3) = 0",
            r"\text{Roots: } x = 1, x = 3"
        ]
    }
