import os
import subprocess
import uuid
import re
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

# Provider SDKs
from google import genai
from groq import Groq
from openai import OpenAI

app = FastAPI(title="Tezla Animator - Free Tier Engine")

# Enable CORS so your Lovable web app can request this endpoint without browser blocks
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Setup directories for static video serving
OS_OUTPUT_DIR = "rendered_videos"
os.makedirs(OS_OUTPUT_DIR, exist_ok=True)
app.mount("/videos", StaticFiles(directory=OS_OUTPUT_DIR), name="videos")

class RenderRequest(BaseModel):
    prompt: str

SYSTEM_PROMPT = """
You are a Manim Python script generator for educational videos.
Your output MUST contain ONLY valid Python code using the Manim Community library.
Do NOT include markdown formatting or backticks (e.g., no ```python).

Rules:
1. Import statements MUST include:
   from manim import *
   from manim_voiceover import VoiceoverScene
   from manim_voiceover.services.edge import EdgeService

2. Define a single scene class named `GeneratedScene(VoiceoverScene)`.
3. In `construct(self)`:
   - Initialize voice: `self.set_speech_service(EdgeService(voice="en-NG-EzinneNeural"))`
   - Wrap visual animations in voiceover blocks:
     with self.voiceover(text="Explanation text here...") as tracker:
         self.play(Write(eq), run_time=tracker.duration)

4. Use raw strings `r"..."` for all MathTex expressions to avoid unescaped backslash crashes.
"""

def clean_code_block(code_text: str) -> str:
    """Strips markdown python wrappers if generated by AI models."""
    cleaned = re.sub(r"^```(?:python)?", "", code_text.strip(), flags=re.MULTILINE)
    cleaned = re.sub(r"```$", "", cleaned.strip(), flags=re.MULTILINE)
    return cleaned.strip()

def generate_code_with_fallback(prompt: str) -> tuple[str, str]:
    """Tries Gemini -> Groq -> OpenRouter in sequence."""
    full_prompt = f"{SYSTEM_PROMPT}\n\nGenerate a narrated Manim scene for: {prompt}"

    # --- TIER 1: GEMINI FREE TIER ---
    gemini_key = os.getenv("GEMINI_API_KEY")
    if gemini_key:
        try:
            client = genai.Client(api_key=gemini_key)
            response = client.models.generate_content(
                model="gemini-2.5-flash",
                contents=full_prompt
            )
            if response.text:
                print("Generated code via Gemini Free Tier")
                return clean_code_block(response.text), "Gemini"
        except Exception as e:
            print(f"Gemini Free Tier error ({str(e)}). Switching to Groq...")

    # --- TIER 2: GROQ FREE TIER ---
    groq_key = os.getenv("GROQ_API_KEY")
    if groq_key:
        try:
            client = Groq(api_key=groq_key)
            response = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Generate a narrated Manim scene for: {prompt}"}
                ],
                temperature=0.2
            )
            content = response.choices[0].message.content
            if content:
                print("Generated code via Groq Free Tier")
                return clean_code_block(content), "Groq"
        except Exception as e:
            print(f"Groq Free Tier error ({str(e)}). Switching to OpenRouter...")

    # --- TIER 3: OPENROUTER FREE TIER ---
    openrouter_key = os.getenv("OPENROUTER_API_KEY")
    if openrouter_key:
        try:
            client = OpenAI(
                base_url="[https://openrouter.ai/api/v1](https://openrouter.ai/api/v1)",
                api_key=openrouter_key,
            )
            response = client.chat.completions.create(
                model="meta-llama/llama-3.3-70b-instruct:free",
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"Generate a narrated Manim scene for: {prompt}"}
                ],
                temperature=0.2
            )
            content = response.choices[0].message.content
            if content:
                print("Generated code via OpenRouter Free Tier")
                return clean_code_block(content), "OpenRouter"
        except Exception as e:
            print(f"OpenRouter Free Tier error: {str(e)}")

    raise HTTPException(
        status_code=500,
        detail="All free AI tiers (Gemini, Groq, OpenRouter) failed or reached rate limits."
    )

@app.get("/")
def health_check():
    """Root route health check so browser test displays online status."""
    return {
        "status": "online",
        "service": "Tezla Animator - Manim Engine",
        "version": "1.0.0"
    }

@app.post("/generate-video")
def generate_math_video(req: RenderRequest):
    job_id = str(uuid.uuid4())[:8]
    script_filename = f"temp_{job_id}.py"

    # Step 1: Request Manim Python Code via Fallback Chain
    generated_code, used_provider = generate_code_with_fallback(req.prompt)

    # Step 2: Write temporary Python file
    with open(script_filename, "w", encoding="utf-8") as f:
        f.write(generated_code)

    # Step 3: Render Video via Manim CLI
    video_output_path = os.path.join(OS_OUTPUT_DIR, f"{job_id}.mp4")

    manim_cmd = [
        "manim",
        "-ql",
        "--media_dir", "./media",
        script_filename,
        "GeneratedScene"
    ]

    try:
        subprocess.run(manim_cmd, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        expected_manim_output = os.path.join("media", "videos", f"temp_{job_id}", "480p15", "GeneratedScene.mp4")

        if os.path.exists(expected_manim_output):
            os.rename(expected_manim_output, video_output_path)
        else:
            raise FileNotFoundError(f"Render output missing at {expected_manim_output}")

    except subprocess.CalledProcessError as err:
        error_msg = err.stderr.decode("utf-8") if err.stderr else str(err)
        raise HTTPException(
            status_code=400,
            detail=f"Manim Rendering Error: {error_msg}"
        )
    finally:
        if os.path.exists(script_filename):
            os.remove(script_filename)

    # Step 4: Return Video Path URL and Provider Metadata
    return {
        "status": "success",
        "job_id": job_id,
        "provider_used": used_provider,
        "video_url": f"/videos/{job_id}.mp4"
    }
